# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # latest Black version
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # ✅ a valid tag for the isort mirror
    hooks:
      - id: isort
