artifacts_root : artifacts


data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url: "https://drive.google.com/drive/folders/1sIfBl1cJbuqqsWQnRvlqNqGX6i-9xst3?usp=sharing"
  local_data_file : artifacts/data_ingestion/100_Unique_QA_Dataset.zip
  unzip_dir : artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["100_Unique_QA_Dataset.csv"]

data_transformation:
  root_dir : artifacts/data_transformation
  data_path : artifacts/data_ingestion/Dataset/100_Unique_QA_Dataset.csv
  vocab_file_path: artifacts/data_transformation/Vocab
  output_dir : artifacts/data_transformation/Preprocessed_Data
  
model_trainer:
  root_dir : artifacts/model_trainer
  data_path : artifacts/data_transformation/Preprocessed_Data/preprocessed_data.csv
  vocab_file_path: artifacts/data_transformation/Vocab/vocab.json
  output_path : artifacts/model_trainer

model_evaluation:
  root_dir: artifacts/model_evaluation
  saved_model_path: artifacts/model_trainer/qa_rnn.pth
  model_metrics_json: artifacts/model_evaluation
  data_path : artifacts/data_transformation/Preprocessed_Data/preprocessed_data.csv
  vocab_file_path: artifacts/data_transformation/Vocab/vocab.json

model_prediction:
  saved_model_path : artifacts/model_trainer/qa_rnn.pth
  vocab_file_path: artifacts/data_transformation/Vocab/vocab.json
